spring.application.name=Spring
server.port=8080

# baglanti config
spring.datasource.url=jdbc:sqlserver://localhost:${DB_PORT};databaseName=ITAssetManagementDB;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_LOGIN}
spring.datasource.password=${DB_PWD}

#tablolari iliskisel GUIDleri ve kisitlamalari otomatik yonetir
#it validates both db and models if cant success than project wont run
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# Spring Security korumasini gecici olarak bypass etme ayarlari
spring.security.user.name=admin
spring.security.user.password=12345
