spring.application.name=Spring
server.port=8080

# ba?lant? config
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=ITAssetManagementDB;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_LOGIN}
spring.datasource.password=${DB_PWD}

#tablolar? ili?kisel GUIDleri ve k?s?tlamalar? otomatik yönetir
spring.jpa.hibernate..ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# Spring Security korumas?n? geçici olarak bypass etme ayarlar?
spring.security.user.name=admin
spring.security.user.password=12345
